### ISSUE TITLE
remove extra line breaks

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-easter-egg#15]
the extra `console.log('\n\n');`  are not necessary 
![image](https://cloud.githubusercontent.com/assets/128755/9137887/b66f07c0-3cee-11e5-86b3-ba58404dbca3.png)
## Expected

(like hacks.mozilla.org)

![image](https://cloud.githubusercontent.com/assets/128755/9137917/d8dd5cc6-3cee-11e5-94a8-d80d7896a711.png)
## Actual

![](http://v14d.com/i/55c4c051a9e43.jpg)

**Comment by pdehaan** [comment]
Actually, I think the newlines ARE needed, but in the beginning of the other dinosaur string. Here's how it looks in Chrome:

![create_a_firefox_account](https://cloud.githubusercontent.com/assets/557895/9140659/a6b1ed9a-3ce7-11e5-8908-0bea683708b6.png)

Note that it looks like the first line with the top of the dinosaur's head is shifted due to Chrome's leading timestamps.

**Comment by vladikoff** [comment]
Okay then new lines should probably be part of the same `console.log` message then

**Comment by TDA** [comment]
referencing #5 . Added the newlines to fix that issue. Moving newlines to the same console log in #16

**Comment by vladikoff** [comment]
fixed in https://github.com/mozilla/fxa-easter-egg/commit/71e61f05ab7c0b7c7fcef8ced12d1969503f5968
